ktor:
  application:
    modules:
      - hu.netcode.auth.ApplicationKt.module
  deployment:
    port: $PORT
    watch:
      - classes
      - resources
  development: $DEV
aws:
  stage: "$STAGE:dev"
jwt:
  secret: $JWT_SECRET
cache:
  baseUrl: $CACHE_SERVICE_BASE_URL
